# window and pane start index
set -g base-index 1
set -g pane-base-index 1

# automatically set window title
set-option -g set-titles on
set -g set-titles-string '#{session_name} • #{window_index} • #{pane_title}'
setw -g automatic-rename on

# enable 256-colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# prefix
unbind C-b
set -g prefix C-space
bind space send-prefix

set -g set-clipboard on

#### Key bindings

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind p paste-buffer

#bind t send-key C-t
# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

bind C run-shell 'TMUX= tmux neww -d \; switch-client -n'

# vim-like split pane switching
bind -r C-k select-pane -U 
bind -r C-j select-pane -D 
bind -r C-h select-pane -L 
bind -r C-l select-pane -R 

# similar to my tab switching binding in vim
bind -r l next-window
bind -r h previous-window

bind -r j switch-client -n
bind -r k switch-client -p

# Resizing pane
# awkward but I want to use hjkl and avoid vim bindings
bind -r M-k resize-pane -U 5
bind -r M-j resize-pane -D 5
bind -r M-h resize-pane -L 5
bind -r M-l resize-pane -R 5

# Vimlike splitting
unbind s
unbind v
bind s split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

# Moving window
bind -r C-Left swap-window -t -1 \; select-window -t -1
bind -r C-Right swap-window -t +1 \; select-window -t +1

# fzf session
bind -r f run-shell "tmux neww /home/bradley/.local/bin/tmux-sessionizer"

# set history limit
set -g history-limit 10000

# no delay for escape key press
set -sg escape-time 0

# status line
set -g status-justify centre
set -g status-style 'fg=blue,bg=#1a212e'
set -g status-interval 2

# window status
setw -g window-status-separator '#[fg=blue] | '
setw -g window-status-format '#[fg=blue]#I #W#[fg=blue]'
setw -g window-status-current-format '#[fg=magenta]#I #W#[fg=blue]'

### statusbar
set -g status-position bottom
#set -g status-left '#[fg=black,bg=magenta,bold] #S #[fg=magenta,bg=black,nobold,noitalics,nounderscore]                       '
set -g status-left '#[fg=#1a212e,bg=magenta,bold] #S #[fg=blue,bg=#1a212e,nobold,noitalics,nounderscore]'
set -g status-left-length 24
#set -g status-right ' #[fg=blue]#[fg=black]#[bg=blue] %I:%M %p #[bg=default,fg=default]'
set -g status-right ' #[fg=black,bg=blue,bold] %I:%M %p #[bg=#default,fg=blue,nobold]'
set -g status-right-length 24

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# modes
setw -g clock-mode-colour colour135
setw -g clock-mode-style 12

# shortcut bindings
bind -r i run-shell 'tmux neww tmux-cht'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
