general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = killall -USR1 hyprlock
    before_sleep_cmd = hyprlock
    after_resume_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Turn off keyboard backlight
listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:keyboard: set 0
    on-resume = brightnessctl -rd rgb:keyboard:
}

# 3. Lock the screen via hyprlock
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 4. Turn off screen displays to save power
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 5. Suspend PC com
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
