"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[package]
disabled = true

