# Colors

foreground #a5b0c5
background #1a212e

# Black
color0  #0c0e15
color8  #0c0e15

# Red
color1  #f65866
color9  #992525

# Green
color2  #8bcd5b
color10 #8bcd5b

# Yellow
color3  #efbd5d
color11 #8f610d

# Blue
color4  #41a7fc
color12 #41a7fc

# Magenta
color5  #c75ae8
color13 #862aa1

# Cyan
color6  #34bfd0
color14 #1b6a73

# White
color7  #93a4c3
color15 #6c7d9c

# Tab Bar

active_tab_foreground   #1a212e
active_tab_background   #a5b0c5
inactive_tab_foreground   #a5b0c5
inactive_tab_background   #1a212e
