#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Bradley Wood"
email = "52896759+BradleyLWood@users.noreplay.github.com"

[ui]
diff-editor = ["nvim", "-d", "$left", "$right", "$output"]
default-command = "log"

[aliases]
st = ["status"]
l = ["log"]
d = ["diff"]
la = ["log", "-r", "all()"]
le = ["log", "--config", "template-aliases.\"format_short_signature(signature)\"=\"signature.email()\""]
lae = ["log", "-r", "all()", "--config", "template-aliases.\"format_short_signature(signature)\"=\"signature.email()\""]
log-email = ["log", "--config", "template-aliases.\"format_short_signature(signature)\"=\"signature.email()\""]

fetch = ["git", "fetch"]
push = ["git", "push", "--allow-new"]
track = ["bookmark", "track"]

[template-aliases]
"format_short_signature(signature)" = "signature.name()"

